version: "3.9"

services:

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0--port 8080"
  #   depends_on:
  #     - database

  database:
    image: postgres:latest
    volumes:
      - itation-app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  itation-app-db-data:
