"""add tz to ans

Revision ID: 3526b3009969
Revises: 7ab4d3e64ed3
Create Date: 2022-10-04 22:08:45.648651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3526b3009969'
down_revision = '7ab4d3e64ed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
