"""remove unused

Revision ID: 7ab4d3e64ed3
Revises: ab99bff75efe
Create Date: 2022-10-04 20:25:32.954485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab4d3e64ed3'
down_revision = 'ab99bff75efe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'avaliable_task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('avaliable_task', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
