name: Lint and Test

on:
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"
  push:
    branches:
      - dev
      - "refactor/**"
      - "fix/**"
      - "feature/**"
    paths-ignore:
      - "**.md"

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/src/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run linters
        run: |
          source .venv/bin/activate
          make lint
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/src/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run tests
        run: |
          source .venv/bin/activate
          make test
